import names from "@/data/station-names.json";

// Indego's full station roster, including retired stations that still appear
// in trip data. Generated by scripts/build-station-names.mjs.
const STATION_NAMES: Record<string, string> = names;

export function hasStationName(stationId: string): boolean {
  return stationId in STATION_NAMES;
}

export function stationName(stationId: string): string {
  return STATION_NAMES[stationId] ?? `Station ${stationId}`;
}
